### ISSUE TITLE
Placement of toolbar totally breaks HTML

### ISSUE THREAD

**Issue by mariano** [tmaiaroto/li3_perf#10]
I know this is a known issue and you probably have a solution in mind, but since I am using a fixed menubar on top of my viewport, the toolbar is totally hidden.

Therefore I am making a pull request so you can easily place a placeholder in your layout. So whenever the `<!-- LI3_PERF_TOOLBAR -->` is found, it will be replaced with the contents of the actual toolbar. This allows you to keep a proper HTML document, and place the toolbar where you wish (though a bit of CSS trickery might be needed.)

The pull request does not break backwards compatibility as if that expression is not found in the body, the original behavior is maintained.

**Comment by tmaiaroto** [comment]
I know it was an issue, but I didn't have any good ideas yet for solving it. Cool, thanks! Awesome that it's backward compatible too.
